### ISSUE TITLE
Update interface to fix needs found by Hatchet.

### ISSUE THREAD

**Issue by kisaacs** [hdc-arizona/roundtrip#6]
This assumes the disambiguation of Hatchet-local vis wrapper stuff and the lower-level Roundtrip.

**Comment by cscully-allison** [comment]
- [x] Turn Roundtrip into a normal class
- [x] Define a function for loading arbitrary JS files
- [x] Define a function for loading arbitrary CSS files
- [x] Define a function for loading arbitrary HTML "template" files
- [x] Define a function for binding multiple jupyter scope variables to multiple javascript scope variables
- [x] Define a function for retrieving data from javascript code
- [x] Investigate a means to watch a Jupyter cell and update vis when that cell updates

**Comment by cscully-allison** [comment]
Got all this done and done :)
